// colors and dummy data

export const colours = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
  lightAppBackGround: '#f1f7eb',
  darkAppBackGround: '#a5c288',
};

export const productItems = [
  {
    productID: 'p1',
    productTypeID: 'p1',
    productType: 'Processor',
    productFor: 'Desktop',
    productCompany: 'Intel',
    productModel: 'Core 2 Dual (1.6 - 2.5)',
    productImageURL:
      'https://www.notebookcheck.net/uploads/tx_nbc2/img_1614_intel-core2-duo_03.jpg',
    productQuantity: 175,
    productPrice: 0,
    productModelNo: 'abc1',
    productDescription: '2GB RAM PC3',
  },
  {
    productID: 'p2',
    productTypeID: 'p2',
    productType: 'Processor',
    productFor: 'Desktop',
    productCompany: 'Intel',
    productModel: 'Core 2 Dual (2.6 - 3.3)',
    productImageURL:
      'https://www.notebookcheck.net/uploads/tx_nbc2/img_1614_intel-core2-duo_03.jpg',
    productQuantity: 423,
    productPrice: 0,
    productModelNo: 'abc2',
    productDescription: '2GB RAM PC4',
  },
  {
    productID: 'p3',
    productTypeID: 'p3',
    productType: 'Processor',
    productFor: 'Desktop',
    productCompany: 'Intel',
    productModel: 'Dual Core (1.6 - 2.5)',
    productImageURL:
      'https://static-01.daraz.com.bd/p/mdc/83bc2ef0af141fc357641c48b0aca2fe.jpg',
    productQuantity: 270,
    productPrice: 0,
    productModelNo: 'abc3',
    productDescription: '2GB RAM PC5',
  },
  {
    productID: 'p4',
    productTypeID: 'p4',
    productType: 'Processor',
    productFor: 'Laptop',
    productCompany: 'Intel',
    productModel: 'Dual Core (2.6 - 3.3)',
    productImageURL:
      'https://static-01.daraz.com.bd/p/mdc/83bc2ef0af141fc357641c48b0aca2fe.jpg',
    productQuantity: 785,
    productPrice: 0,
    productModelNo: 'abc4',
    productDescription: '2GB RAM PC6',
  },
  {
    productID: 'p5',
    productTypeID: 'p5',
    productType: 'Processor',
    productFor: 'Server',
    productCompany: 'Intel',
    productModel: 'Dual core 1st Generation',
    productImageURL:
      'https://static-01.daraz.com.bd/p/mdc/83bc2ef0af141fc357641c48b0aca2fe.jpg',
    productQuantity: 27,
    productPrice: 0,
    productModelNo: 'abc5',
    productDescription: '2GB RAM PC7',
  },
  {
    productID: 'p6',
    productTypeID: 'p6',
    productType: 'Processor',
    productFor: 'Server',
    productCompany: 'Intel',
    productModel: 'Dual core 3rd Generation',
    productImageURL:
      'https://static-01.daraz.com.bd/p/mdc/83bc2ef0af141fc357641c48b0aca2fe.jpg',
    productQuantity: 56,
    productPrice: 0,
    productModelNo: 'abc6',
    productDescription: '2GB RAM PC8',
  },
  {
    productID: 'p7',
    productTypeID: 'p7',
    productType: 'Processor',
    productFor: 'Server',
    productCompany: 'Intel',
    productModel: 'Dual core 4th Generation',
    productImageURL:
      'https://static-01.daraz.com.bd/p/mdc/83bc2ef0af141fc357641c48b0aca2fe.jpg',
    productQuantity: 17,
    productPrice: 0,
    productModelNo: 'abc7',
    productDescription: '2GB RAM PC9',
  },
  {
    productID: 'p8',
    productTypeID: 'p8',
    productType: 'Processor',
    productFor: 'Server',
    productCompany: 'Intel',
    productModel: 'Dual core 6th Generation',
    productImageURL:
      'https://static-01.daraz.com.bd/p/mdc/83bc2ef0af141fc357641c48b0aca2fe.jpg',
    productQuantity: 3,
    productPrice: 98000,
    productModelNo: 'abc8',
    productDescription: '2GB RAM PC10',
  },
  {
    productID: 'p9',
    productTypeID: 'p9',
    productType: 'Processor',
    productFor: 'Server',
    productCompany: 'Intel',
    productModel: 'Core i3 1st Generation',
    productImageURL:
      'https://5.imimg.com/data5/SELLER/Default/2021/3/KW/HH/XG/51533752/intel-i3-1st-gen-processor-500x500.jpg',
    productQuantity: 21,
    productPrice: 99680,
    productModelNo: 'abc9',
    productDescription: '2GB RAM PC11',
  },
];
